# fly.toml app configuration file generated for bruno-jobs on 2023-04-23T17:34:25-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bruno-jobs"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
